#!/usr/bin/env sh
set -eu
if [ ! "$#" = "1" ]; then
    echo "Usage: gen-curses-h NCURSES_PATH"
    exit 1
fi
ncurses_path=$1
inc=$ncurses_path/include
out=inc/curses.h
tmp=${out}.processing
cat $inc/curses.head > $tmp
$inc/MKkey_defs.h >> $tmp
cat $inc/curses.tail >> $tmp
